[book]
title = "AREA Documentation"
authors = ["CrackedOnTiti"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "coal"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
